### ISSUE TITLE
full entry modal

### ISSUE THREAD

**Issue by richardletshacks** [HorionContinued/sigs#1]
When clicking on an entry in the list, a popup with extended information should appear.
This functionality should not compromise on the usability of a list entry, meaning you shouldn't be required to open this modal.

We could display stuff like possible implementations, this would require us to extend the metadata type.

[progress checkboxes incoming, too lazy rn]

**Comment by dorian-K** [comment]
If a function is virtual, also show information about the vtable (signature, etc.) if present in the database
