### ISSUE TITLE
Which version does it apply to？

### ISSUE THREAD

**Issue by VioletOnion** [HorionContinued/sigs#4]
Which version does it apply to？

**Comment by richardletshacks** [comment]
Hasn't been updated in a while. Should be on version `1.19.51`.

**Comment by VioletOnion** [comment]
OK. Did it support other versions before

**Comment by FutureStrime** [comment]
How did you get those signatures?

**Comment by VioletOnion** [comment]
Perhaps by decompiling BDS

**Comment by CloudWaddie** [comment]
Not to re-open but in case this is useful:
Older versions of the BSD included the PDB. You can use a BinDiff tool on an analysed windows client binary and then name them using the PDB. You can use a sigtool to auto generate signatures.
